README.md, lib/med_installer/solr.rb
update med_installer solr.rb to current solr
add a few fixes to the README.md file
Did a second PR because I didn't squash my two commits in the first one.
=> update med_installer solr.rb to current solr and update readme.md

app/assets/stylesheets/dromedary.scss
=> fix problem with two constraint panels by hiding one

Gemfile.lock
No changes other than to the Gemfile.lock
=> Update loofah due to security vulnerabilities

indexer/xslt/Common.xsl, indexer/xslt/DefOnly.xsl, indexer/xslt/EtymOnly.xsl, indexer/xslt/FormOnly.xsl, indexer/xslt/WholeEntry.xsl, indexer/xslt/test/README, indexer/xslt/test/Untitled.xml, indexer/xslt/test/liften_ETYM.xml, indexer/xslt/test/liften_FORM.xml, indexer/xslt/test/liften_def1.xml, indexer/xslt/test/liften_def2.xml
…m, etym.  Added test fragments.
=>  added XSLT for fragments

app/controllers/catalog_controller.rb
A stupid one-line change to provide correspondence with the JIRA ticket
=>  MEC-73 Remove 'grammatical usage' facet

app/views/catalog/_index_header_entry.html.erb
Bill is the line " <% sense = doc_presenter.senses.first %>" correct in this file. Seems to work.
File: app/views/catalog/_index_header_entry.html.erb
=> Improved search xml translation and quote and senses display

Gemfile, Gemfile.lock
We're hosting two gems there
* **middle_english_dictionary** is the over-engineered object
representing the whole entry structure
* **xpath_list** is used to generate a list of xpaths and rare_xpaths
so we can find all the edge cases
=> Update Gemfile to pull from https://gems.www.lib.umich.edu/

Gemfile, app/controllers/catalog_controller.rb, indexer/entry_indexer.rb, lib/med_installer/convert.rb, solr/med/conf/schema.xml, solr/med/conf/solrconfig.xml, solr/med/conf/solrconfig_med/everything_search.xml
Three more searches that result in the same search results page full of dictionary entries. 
Use of any of them requires a re-convert and re-index
* `bin/dromedary convert ../data`
* `bin/dromedary index entries ../data`
=> MEC-92 MEC-95 MEC-96 Etymology, Def/Notes, and Anywhere searches

app/assets/stylesheets/main.scss, app/views/catalog/_index_skiplinks.html.erb, app/views/catalog/_search_form.html.erb, app/views/catalog/home.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header_navbar.html.erb
Update the two search bars, styling, responsiveness, fix some semantics...
=> MEC-72 update search bars

Gemfile, Gemfile.lock
=> Fix gemfile to deal with weirdnesses with mysql, zip, and noko

Gemfile, Gemfile.lock, lib/med_installer/convert.rb
Pull language expansions from new tags in data
* Update version of med gem
* Rescue new med expection classes
* Force specific version of med gem
=> Parse new versions of input files for language and errrors

app/helpers/med_quotes_helper.rb, app/views/catalog/_show_default.html.erb
Add working quotes
Add better error checking
=> improve quote display and controls

lib/annoying_utilities.rb, lib/med_installer/solr.rb
As reported by @gordonleacock in the slack channel
=> Fix getting solr port from withing bin/dromedary solr utilities

app/assets/stylesheets/dromedary.scss, app/assets/stylesheets/main.scss, app/views/_secondary_util_links.html.erb, app/views/catalog/home.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header_navbar.html.erb
Update the fact panel layout on home page. 
Updated the secondary nav panel semantics, remove extra bootstrap, and styled it per the designs. Still need to add a conditional to show active class if a view is active. The style for active is in the .scss file. 
Minor footer updates.
=> Style and layout updates for home, nav, and footer

README.md, docs/autocomplete_setup.md, docs/extractions_and_conversion.md
* Pull everything out of the README besides the quick setup and update procedures
* Add other stuff to the `docs` directory.
=> Update the documentation with new procedures

app/assets/stylesheets/main.scss, app/controllers/catalog_controller.rb, app/views/catalog/_index_header_entry.html.erb, app/views/catalog/index.html.erb
First phase of changes to the catalog/search results page.
=> Beginning style changes to catalog results

app/views/catalog/_show_default.html.erb
**Changes:**
- Toggles controls for hiding and showing quotes
- Updates the title for the supplement notes section per @pfs
=> toggle-quote-control within each sense

indexer/xslt/CitOnly.xsl, indexer/xslt/Common.xsl, indexer/xslt/EytmOnly.xsl, indexer/xslt/FormOnly.xsl, indexer/xslt/test/smakke_n.xml
Added spans and class="TAG_NAME" around most tags.  Also added EytmOnly.xsl
=> added spans and classes around most tags

Gemfile, Gemfile.lock, app/presenters/dromedary/index_presenter.rb, app/views/catalog/_index_header_entry.html.erb
Similar to what's on the full-page entry display. @bridgetburke, once this is merged you can do your magic on this stuff as well.
=> Minor changes to put entry index card into divs instead of tables

app/controllers/catalog_controller.rb
=> MEC-131 Change facet name to "Subject Labels"

app/controllers/catalog_controller.rb
Exactly as small as you'd expect.
=> Change order of search options

app/views/catalog/show_entry/_sense.html.erb
Otherwise we get empty parens.
=> Only output eg subdef_entry letter if there is one

app/views/bibliography/_document.html.erb, app/views/bibliography/_document_list.html.erb, app/views/bibliography/_home.html.erb, app/views/bibliography/_index_header_entry.html.erb, app/views/bibliography/_search_results.html.erb, app/views/bibliography/index.html.erb
Muddling my way through Rails's view path nonsense. Think I've got what I need for bib.
=> Get the bib templates to talk to each other instead of the catalog stuff

Gemfile, Gemfile.lock, app/controllers/bibliography_controller.rb, app/presenters/bibliography/index_presenter.rb, app/presenters/dromedary/index_presenter.rb, app/views/bibliography/_index_header_bib.html.erb, config/application.rb, lib/dromedary/xslt_utils.rb, lib/med_installer/index.rb
Get everything in place for Bib search results so styling can begin
=> Bib search results display

Gemfile, Gemfile.lock, app/controllers/bibliography_controller.rb, app/presenters/bibliography/index_presenter.rb, app/views/bibliography/_show_default.html.erb, app/views/bibliography/show_bib/_ms.html.erb, indexer/bib_indexing_rules.rb, indexer/xslt/bib/Common.xsl, lib/med_installer/convert.rb, solr/med/conf/schema.xml, solr/med/conf/solrconfig_med/bib_searches/lalme_search.xml
This will require grabbing new versions of entries.json.gz and bib_all.xml from the Box account and doing a full index with `bin/dromedary index full /path/to/entries.json.gz /path/to/bib_all.xml`
=> Incorporate LAEME data into indexing, search, and display

app/views/bibliography/_show_default.html.erb, app/views/bibliography/show.html.erb
**Bib Show page**
Remove tools and move (now empty) sidebar to the left.
=> MEC-163 Move sidebar + tools from Bib show

app/assets/stylesheets/main.scss, app/views/catalog/_show_default.html.erb, app/views/catalog/show_entry/_sense.html.erb
Cleans up dictionary quotes and starts on the supplement section. The rest of the supplements will be done in MEC-177.
=> MEC-165 Dictionary quote clean-up

app/assets/stylesheets/main.scss, app/assets/stylesheets/mlib-styles.css, app/views/bibliography/home.html.erb, app/views/quotes/home.html.erb
Home pages for Bib and Quotations.
Also fixed the search bars that were driving me crazy.
=> MEC-175 MEC-176 Bib and Quotation Home Pages

app/controllers/bibliography_controller.rb, app/controllers/catalog_controller.rb
...for bib and dict. Still need something understandable for quote-that-includes-the-stencil
=> Use consistent search label 'Entire entry'

app/controllers/quotes_controller.rb
As per https://docs.google.com/document/d/10dtsK1PeFt4zUeWbKkSObvPg5Uzg90GXdgrM2NS4TCg
=> Update quotation search labels

app/assets/stylesheets/main.scss, app/controllers/quotes_controller.rb, app/views/catalog/splash.html.erb
Fixes the columns after removing the Corpus. Also a little bit of organizing.
=> MEC-189 Splash page 2.0

indexer/bib_indexing_rules.rb, solr/med/conf/schema.xml, solr/med/conf/solrconfig_med/bib_searches/manuscript_search.xml
So manuscript searches like `Hrl 4011` will get what you want
This will necessitate a reindex of teh bibliography:
```
bin/dromedary index bib ../path/to/bib_all.xml
```
=> Index the manuscript abbreviation (REF attribute) and <CITE>

app/assets/stylesheets/main.scss, app/views/bibliography/_per_page_widget.html.erb, app/views/bibliography/_search_header.html.erb, app/views/catalog/_constraints.html.erb, app/views/catalog/_constraints_element.html.erb, app/views/catalog/_per_page_widget.html.erb, app/views/catalog/_sort_and_per_page.html.erb, app/views/catalog/_sort_widget.html.erb, app/views/quotes/_per_page_widget.html.erb, app/views/quotes/_search_header.html.erb
Updates for MEC-187
- Removes constraints from top of search results across catalog, bib, and quotes
- Restyle search results on the left sidebar, including making them readable for long filters 'Parts of Speech or Origin, e.g.', changing color, icon
- Remove Sort by Results # across catalog, bib, and quotes
Still need to add the search value after results but I think that may need to be best done in a helper?
=> MEC-187 Change search criteria display

app/assets/images/external-link-white.svg, app/assets/stylesheets/main.scss, app/views/bibliography/_per_page_widget.html.erb, app/views/bibliography/_search_header.html.erb, app/views/catalog/_constraints.html.erb, app/views/catalog/_constraints_element.html.erb, app/views/catalog/_per_page_widget.html.erb, app/views/catalog/_sort_and_per_page.html.erb, app/views/catalog/_sort_widget.html.erb, app/views/catalog/home.html.erb, app/views/catalog/splash.html.erb, app/views/quotes/_per_page_widget.html.erb, app/views/quotes/_search_header.html.erb, app/views/shared/_footer.html.erb
Adds an external link icon and alt text to notify that an external link is being opened (for current Corpus link and splash page Chaucer image).
This is a usability and a11y fix, not in a Jira ticket.
=> External links

app/presenters/bibliography/index_presenter.rb, app/views/bibliography/_show_default.html.erb, solr/med/conf/schema/middle_english_types.xml
Need to be changed to actually be visible against the white background.
=> put external links on e-editions

indexer/xslt/_CitOnly.xsl
Doesn't eliminate spaces before the colon; need XSLT help on that.
=> Move colon to correct place in quotation display for entry show

app/presenters/quotes/index_presenter.rb, app/views/quotes/_index_header_quote.html.erb, indexer/main_indexing_rules.rb, indexer/quote/basic_rules.rb, indexer/quote/quote_indexer.rb, lib/serialization/indexable_quote.rb, solr/med/conf/schema.xml
...by putting a '?' before them.
=> Update indexing to deal with dubious entries

app/assets/images/external-link-blue.svg, app/assets/stylesheets/main.scss, app/views/bibliography/_show_default.html.erb, app/views/bibliography/show_bib/_ms.html.erb, app/views/catalog/_show_default.html.erb
Add external link icon for Bib, update Bib show page, remove responsive table class to fix horizontal scroll.
=> MEC-173 + MEC-195 Bib Show page updates

app/assets/images/external-link-blue.svg, app/assets/stylesheets/main.scss, app/views/bibliography/_index_header_bib.html.erb, app/views/bibliography/_show_default.html.erb, app/views/bibliography/show_bib/_ms.html.erb, app/views/catalog/_show_default.html.erb, app/views/quotes/_index_header_quote.html.erb
Update bib search results. Also added a few minor changes to quote results while I was in there because there wasn't a ticket for it.
=> Bib results

app/assets/stylesheets/main.scss, app/views/shared/_footer.html.erb, app/views/static/mec_copyright.erb
Reuse styling from "about" page.
=> Add and style copyright page

app/assets/stylesheets/main.scss, app/views/application/_search_header.html.erb, app/views/bibliography/_search_header.html.erb, app/views/bibliography/_zero_results.html.erb, app/views/bibliography/index.html.erb, app/views/catalog/_search_header.html.erb, app/views/catalog/_zero_results.html.erb, app/views/catalog/index.html.erb, app/views/quotes/_search_header.html.erb, app/views/quotes/_zero_results.html.erb, app/views/quotes/index.html.erb
=> Mec 197/no results

app/views/bibliography/home.html.erb, app/views/catalog/home.html.erb, app/views/shared/_footer.html.erb, app/views/static/about_med.html.erb
Fix links and add text descriptions, plus @pfs new About the Med text.
=> Text changes

bin/dromedary, config/application.rb, config/load_local_config.rb, config/settings/development.yml, indexer/main_indexing_rules.rb, lib/annoying_utilities.rb, lib/med_installer/convert.rb, lib/med_installer/index.rb
Change the utilities to just assume everything is in a single data directory as defined in the Ettin configuration.
=> Single data dir

app/assets/stylesheets/main.scss
Cheat by just hiding it for now using css.
=> Remove query text from left-hand-side.

bin/dromedary, lib/med_installer.rb, lib/med_installer/remote.rb, lib/med_installer/solr.rb, solr/med/conf/solrconfig.xml
Add better tooling support:
* solrconfig.xml will now take a library location based on `Dromedary.config.data_dir`
* Add fauxpaas commands under the `bin/dromedary remote` prefix
=> Better tooling

app/assets/stylesheets/main.scss, app/assets/stylesheets/mlib-styles.css
Removes the Mlibrary default background color focus and updates other areas on the UI as well.
Added **some** backward compatibility for IE 10/11. More work (if desired) will need a ticket in the next round.
=> Update focus and address some IE issues

app/assets/stylesheets/dromedary.scss, app/assets/stylesheets/main.scss, app/assets/stylesheets/mlib-styles.css
Update font-family, fix typo, and update font-size across the work.
=> Font update

app/assets/stylesheets/main.scss, app/assets/stylesheets/mlib-styles.css
- Updated flex prefixes and styles for support back to Firefox 45 (fixed customer email from August 1)
- Minor styling updates to clean up responsive forms and spacing
=> Firefox flex updates + responsive styles

app/assets/javascripts/static.js, app/models/search_builder.rb, app/views/catalog/_search_form.html.erb
...instead of yogh.
* Change keyboard icon to produce ezh
* Automatically convert yogh to ezh, in case someone pastes it in.
=> Take into accoutn that data uses  ezh

app/controllers/bibliography_controller.rb, app/controllers/catalog_controller.rb, app/controllers/quotes_controller.rb
Dictionary (a.k.a. Catalog), Bibliography, and Quotes search appears to be working now.
=> controllers fixes

.docker/branch.dockerfile, .github/workflows/build-branch-image.yml
build branch image github action
=> build branch image

.docker/branch.dockerfile, .dockerignore, .github/workflows/build-branch-image.yml
Set environment variable BUNDLE_RUBYGEMS__PKG__GITHUB__COM value equal to secrets.GH_PACKAGE_READ_TOKEN for bundle install.
=> build branch image changes

.dockerignore, Dockerfile, README.md, config/application.rb, docker-compose.alt, docker-compose.bak, solr/.dockerignore, solr/Dockerfile, solr/solr-amd64.dockerfile, solr/solr-arm64.dockerfile
Alternative docker-compose for local development which uses a local simple solr cloud container.
=> docker-compose.alt

app/controllers/admin_controller.rb, app/models/med_solr_collection.rb, app/models/med_solr_collections.rb, app/views/admin/_collection_row.html.erb, app/views/admin/_force_release_row.html.erb, app/views/admin/home.html.erb, app/views/catalog/_related_entries.html.erb, bin/delete_all_med_preview_stuff.rb, compose.yml, config/application.rb, config/load_local_config.rb, config/routes.rb, lib/dromedary/services.rb
A few things:
* Build up real classes for a solr collection and a set of those collections and break them out into their own models
* Base the controller and views on those new classes
* Build up a "force release" table at the bottom of the admin screen
* Make sure to delete configsets when collections are deleted
=> Refactor admin

app/controllers/bibliography_controller.rb, app/controllers/quotes_controller.rb
...in addition to the already-fixed orth search
=> Force edismax handler for quotations and bib searches
