mlibrary/dromedary

app/controllers/catalog_controller.rb
Adds these solr fields to the show page:
config.add_show_field 'headword', label: 'Headwords'
config.add_show_field 'pos_abbrev', label: 'Gramatical Usage (POS ABBREV)'
config.add_show_field 'pos_raw', label: 'Gramatical Usage (POS RAW)'
config.add_show_field 'discipline_usage', label: 'Professional Usage'
config.add_show_field 'etyma_language', label: 'Source Language'
config.add_show_field 'definition_text', label: 'Definition Text'
config.add_show_field 'quote_text', label: 'Quotation Text'
config.add_show_field 'quote_cd', label: 'Quotation CD'
config.add_show_field 'quote_md', label: 'Quotation MD'
config.add_show_field 'quote_rid', label: 'Quotation RID'
config.add_show_field 'quote_title', label: 'Quotation Title'
config.add_show_field 'headerword_exactish', label: 'Headword …
=> Add all terms from solr for show page

app/assets/stylesheets/dromedary.scss, app/views/static/about_med.html.erb
Missing end tag in about page caused footer text to shrink.
Removed extraneous static font size/styling affecting header on about/help pages.
=> Fix header and footer font sizes in about/help pages

app/views/catalog/_related_entries.html.erb, app/views/catalog/_show_header_default.html.erb
adds oed but not doe entries in related definitions.
Also removes default h1 tag in entry (show) page document heading.
I'll create a new ticket for doe entries.
=> adds oed but not doe entries in related definitions

solr/med/conf/schema.xml, solr/med/conf/solrconfig.xml, solr/med/conf/solrconfig_med/suggesters/doe_suggester.xml
Fix oed suggester to use non-borked suggest hander, and add one for doe (including field doe_norm in schema)
Note: requires a reload of the solr core (`bin/dromedary solr reload`).
=> Fix solr suggesters

app/assets/javascripts/bibliography.coffee, app/assets/stylesheets/bibliography.scss, app/controllers/bibliography_controller.rb, app/helpers/bibliography_helper.rb, app/views/bibliography/index.html.erb, app/views/bibliography/show.html.erb, app/views/shared/_header_navbar.html.erb, app/views/shared/nav/_bib.html.erb, config/routes.rb, spec/controllers/bibliography_controller_spec.rb, spec/helpers/bibliography_helper_spec.rb, spec/views/bibliography/index.html.erb_spec.rb, spec/views/bibliography/show.html.erb_spec.rb
**This PR:**
- Adds a very basic controller for the bibliography
- And once solr is set up to search for bib data we can extend the new controller
- Then app/views/bibliography/[index, show].html.erb files can get real content
- And we can add other files to views/ as needed.
- Also cleans up the app/views/shared/_header_navbar.html.erb file.
=> add basic bibliography controller

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/presenters/dromedary/index_presenter.rb, app/views/catalog/_related_entries.html.erb, app/views/catalog/_show_default.html.erb, bin/dromedary, indexer/main_indexing_rules.rb, indexer/pry_session.rb, indexer/quote/basic_rules.rb, indexer/quote/quote_indexer.rb, indexer/writers/localhost.rb, lib/annoying_utilities.rb, lib/med_installer/convert.rb, lib/med_installer/index.rb, lib/med_installer/indexer/entry_json_reader.rb, lib/serialization/indexable_quote.rb, solr/med/conf/schema.xml
Huge, over-large, way-too-big commit that touches too many things.
The main change here is the creation and indexing of quotation objects being injected into the general indexing scheme. These are predicated on changes in the middle_english_dictionary, reflected in the Gemfile as now requiring v. 1.1.0 of that gem.
Muddied in with all of that is new access to OED/DOE links.  
See middle_english_dictionary gem for oed/doelink
access, esp. https://github.com/mlibrary/middle_english_dictionary/pull/5
Also use new conversion/indexing in application and change enough of
the oed/doe templates to not break.
Also:
* Added ./serialization/indexable_quote to lib
* Reorganized ./indexing directory
=> New indexing framework and OED/DOE changes

app/views/catalog/_index_header_entry.html.erb
**Changes:**
- Shows 200 characters of the first sense in each definition
- Add an ellipsis that links to the show page for the definition after the sense
- Cleans up formatting of code
=> make index page show one sense per def. and an ellipsis

config/routes.rb
Rails default is to disallow ids with a dot in them "because the dot is used as a separator for formatted routes". Add an explicit constraint to a route so it works with MED1234.5.
=> MEC-129 Fix routes to allow ids with dot

app/views/catalog/_show_default.html.erb
**Changes:**
- Iterates over multiple notes (if they exist) within a supplement
- A potential problem: If there are supplements without notes the table still displays
- This solution is good until we have xslt for supplements at which time it should be rewritten
- Please merge after the quote control PR
=> handle multiple notes within a supplement

app/views/catalog/_index_header_entry.html.erb
**Changes:**
- Modify the index definition display to match Ben's mock up of two columns: one with the label and one with the definition.
=> add responsive table to index definitions

Gemfile, Gemfile.lock, app/assets/stylesheets/dromedary.scss, app/controllers/catalog_controller.rb, app/helpers/med_quotes_helper.rb, app/presenters/dromedary/index_presenter.rb, app/views/catalog/_index_header_entry.html.erb, app/views/catalog/_show_default.html.erb, app/views/catalog/show_entry/_sense.html.erb, indexer/main_indexing_rules.rb, indexer/writers/localhost.rb, lib/med_installer/index.rb, solr/med/conf/schema.xml, solr/med/conf/solrconfig.xml, solr/med/conf/solrconfig_med/citation_search.xml, solr/med/conf/solrconfig_med/suggesters/doe_suggester.xml, solr/med/conf/solrconfig_med/suggesters/headword_and_forms_suggester.xml, solr/med/conf/solrconfig_med/suggesters/headword_only_suggester.xml, solr/med/conf/solrconfig_med/suggesters/oed_suggester.xml
Use XSL Transforms to display data
Change display of data in the Show page for a dictionary
entry to use XSL transforms found in `indexer/xslt`.
* Changes to the presenter to generate XML nodes that
can be transformed and then provide the raw HTML
to the views
* Split the Show view into a couple files to make it
easier to read
* Change the expand/collapse javascript to target the
entire block that needs hiding.
=> Use XSL for display

app/controllers/catalog_controller.rb, config/routes.rb
* Never see /#{default_path}/index.html
* Change `/catalog` to `/dictionary` for the default path, to better match `/bibliography`
=> MEC-128 Redirect '/catalog' (now '/dictionary') to '/'

app/controllers/catalog_controller.rb, config/autocomplete.yml, lib/med_installer/solr.rb
Necessary to be able to read the solr suggest paths and rebuild the suggest indexes.
=> Move autocomplete config to a config file

app/views/_secondary_util_links.html.erb
This is what puts the little lines under the part of the site where you are (dictionary or bib, eventually quote)
=> Switch "active" page based on controller

app/presenters/dromedary/index_presenter.rb, config/application.rb, lib/med_installer/index.rb
Make a mapping of RIDs  ("HYP..." identifiers) to BibIDs on index and stick it in the 
`config` directory for use when rendering quotations.
=> Rationalize hyp_to_bibID

app/views/catalog/_show_default.html.erb, app/views/catalog/show_entry/_sense.html.erb, app/views/quotes/_index_header_quote.html.erb, indexer/xslt/_CitOnly.xsl
* Quotations whose citation isn't in the bibliography now display
without throwing an error
* Change quote show/hide logic a bit so "Show all" and "Hide all"
maintain consistent show/hide buttons for the individual senses.
=> Fix quotation display

app/assets/stylesheets/main.scss, app/controllers/quotes_controller.rb, app/views/_secondary_util_links.html.erb, app/views/bibliography/home.html.erb, app/views/catalog/_index_header_entry.html.erb, app/views/catalog/home.html.erb, app/views/catalog/splash.html.erb, app/views/layouts/static.html.erb, app/views/quotes/home.html.erb, app/views/shared/_footer.html.erb, app/views/static/_about_sidebar.html.erb, app/views/static/about_med.html.erb, config/locales/en.yml
A suite of more-or-less minor changes to the actual
words used and what's linked.
* Add new "About page" with internal navigation
* Remove links to corpus from all navigation and splash
pages except in the footer
* Add blub text for bib and quotation
* Change "senses on" to "senses in"
* Make home/splash page headings links
* Fix links in left column of footer
=> Changes to text and links

app/presenters/common_presenters.rb, app/presenters/dromedary/index_presenter.rb, app/presenters/quotes/index_presenter.rb, app/views/catalog/_index_header_entry.html.erb, app/views/catalog/_show_default.html.erb, app/views/quotes/_index_header_quote.html.erb, indexer/xslt/Common.xsl, indexer/xslt/_CitOnly.xsl
* Extract common presenter elements in presenters/common.rb
* Fix xsl to render citation in brackets if TYPE="B"
Note: Requires the indexing of 'dubious = "Y"' into solr document for
both Quotation and Dictionary docs when ENTRYFREE[@DUB] == "Y"
=> Mec 180/conditional display elements

indexer/bib_indexing_rules.rb, solr/med/core.properties
This address the problem of not being able to search for "Cmb.Hom" in bib. 
Problem was that I was just getthing the xml text, and had something like `<A>Cmb.Hom.</><B>Hom</B>`, so it was being indexed as a single token "Cmb.Hom.Hom".
=> Index stencils by pieces to avoid running text together

app/controllers/catalog_controller.rb, app/views/catalog/_search_form.html.erb
Headwords and Forms remains the default
=> Move "anywhere" to first place in dictionary search

app/views/static/maintenance_mode.html.erb, bin/dromedary, config/routes.rb, lib/annoying_utilities.rb, lib/med_installer.rb, lib/med_installer/control.rb, lib/med_installer/remote.rb
Fixes maintenance mode to use a flag file, so as to not get
MM branch out of date. New dromedary commands
* bin/dromedary maintenance_mode on
* bin/dromedary maintenance_mode off
Can be run on remote install with
* bin/dromedary remote dromedary staging "maintenance_mode off"
=> Add utility methods to do maintenance_mode route.

Gemfile, Gemfile.lock, indexer/bib_indexing_rules.rb, indexer/main_indexing_rules.rb, indexer/quote/basic_rules.rb, lib/med_installer/index.rb, lib/med_installer/indexer/entry_json_reader.rb, lib/serialization/indexable_quote.rb, solr/med/conf/schema.xml, solr/med/conf/schema/middle_english_char_substitution_patterns.xml, solr/med/conf/schema/middle_english_types.xml, solr/med/conf/solrconfig_med/bib_searches/author_title_search.xml, solr/med/conf/solrconfig_med/bib_searches/everything_search.xml, solr/med/conf/solrconfig_med/bib_searches/stencil_search.xml, solr/med/conf/solrconfig_med/entry_searches/citation_search.xml, solr/med/conf/solrconfig_med/entry_searches/everything_search.xml, solr/med/conf/solrconfig_med/quote_searches/quote_everything_search.xml
Researchers want to be able to search author.title
(e.g., Capgr.Chron) to find particular authors
and manuscripts. This indexing change does this
through two changes:
* Change solr config so that dots are removed
only for headwords
* Add indexing of author.title
These changes are predicated on using the gem
middle_english_dictionary v. 1.6.0 or later,
since the stencil author was inadventantly
left out in the past.
Also:
* Add quote_manuscript to entry/quotation searches
so "LdMisc 108" gives expected results
* Do a mapping from k->c on index and query
=> Indexing changes: author.title, manuscript, k->c

app/models/search_builder.rb, app/presenters/dromedary/index_presenter.rb, app/views/catalog/show_entry/_sensegrp.html.erb, app/views/static/about_med.html.erb, indexer/main_indexing_rules.rb, solr/med/conf/schema.xml, solr/med/conf/schema/middle_english_types.xml, solr/med/conf/solrconfig_med/entry_searches/everything_search.xml, solr/med/conf/solrconfig_med/entry_searches/headword_and_forms_search.xml, solr/med/conf/solrconfig_med/entry_searches/headword_only_search.xml
Better prefix/suffix handling in searches. 
Argh. Why doesn't it pre-populate with the latest commit message??? Pasting.
Searches for, e.g., `-ward` were incorrectly handled in
two ways:
* The `-` was interpreted as a unary NOT (part of edismax)
* The `-` was being thrown away as a junk charactor and/or
as a word boundary.
This commit does the following:
* Add a function to the pipline in `search_builder.rb`
that escapes leading or trailing dashes before they
get sent up to Solr, to avoid the unary negative
interpretation.
* Adds a new fieldType `me_prefix_suffix` that acts like
an exactish ME field (in terms of latinizing for search)
but protects a leading- or trailing dash
* Create a new field, `prefix_suffix` of that type
* Populate the field with regularized headwords iff
the headword …
=> Prefix suffix

app/views/shared/_header_navbar.html.erb
The new website launch created a broken image link for the "M" block image across some sites. This commit adds the correct link for the redirect. 
Note: the Design System will be working on creating stable assets in one place to avoid this in the future.
=> Adds link redirect to fix broken image link

.github/workflows/build-unstable-branch.yml, .gitignore, Dockerfile, Gemfile, compose.yml, config.ru, config/application.rb, config/environments/production.rb, config/load_local_config.rb, config/routes.rb
There are many improvements to the Dockerfile here:
- The Dockerfile is now multi-stage so development and production are accounted for, but separate -- meaning development oriented tools like vim and ripgrep are added only to the locally built development image.
- The cache volumes are now used to hold APT packages, development, and production gems, and produce a clean bundle.
- The app service now runs in development mode, so the normal Rails development reloads work.
- The NodeJS install is moved to nodesource.
- The ruby image is slim by default, and is parameterized.
- The default (last) stage is development, so builds will give you the most likely useful thing by default.
Then, the most important substance here is the relative root URL handling:
- Development no longer uses or …
=> Restructure builds to support relative root and CDN

.gitignore, Gemfile, Gemfile.lock, app/controllers/updates_controller.rb, app/views/layouts/uploader.html.erb, app/views/updates/index.html.erb, compose.yml, config/routes.rb, lib/dromedary/services.rb
This fits together all of the little pieces to use multi-part uploads directly to S3, relieving the form rendering and temp file handling:
- Add Shrine
- Add AWS S3 SDK
- Add content disposition detection
- Add Uppy S3 multi part
- Add layout to load Uppy CSS from CDN in head section
- Load incoming bucket configuration from ENV
- Set up optional Compose env_file (.app.env; requires 2.24+)
- Condition the initialization on ENV vars being present
- Add routes for updates controller
- Add routes for presigned and multipart direct uploads
- Condition the routes on S3 ENV vars being present
- Add basic view to configure and show Uppy interface
- Load Uppy mjs from CDN inline in the view
It's not perfect, but it does work, and it does support pause/retry for partially completed uploads. The …
=> Add minimal Shrine + Uppy updater

app/views/catalog/_related_entries.html.erb
...as per [slack message from PFS](https://mlit.slack.com/archives/C83KQTUGK/p1724693732637709)
Links to DOE (both old format and new) don't seem to be working at all from my home machine; will check to see if it's a DNS issue or something)
=> [DRAFT! Check links!] Update DOE link targets and warning text

lib/med_installer/indexing_steps.rb
On indexing, some subset of the three solr replicas seem to not end up building the suggesters. This is a brute-force
attempt to fix that issue without truly understanding it.
Force a hard commit (finishing off the main indexing) and then sleep for ten seconds.
=> Fix not-all-replicas-have-suggester by forcing hard commit before building suggester indexes

Gemfile, Gemfile.lock, compose.yml, lib/dromedary/services.rb, lib/med_installer/indexing_steps.rb
We were dealing with some instabilities in the k8s cluster in 2024.09 when we wanted to release this, resulting nodes loosing track of zookeeper and suggesters not getting built (calls would time out). Attempt to brute-force this by hitting the individual solr URLs directly, taking advantage of knowledge about how many replicas and what they're called that we'd really rather not have to know.
NOTE: Once it's determined we don't need this hack, tear the relevant code in MedInstaller:IndexingSteps#index (after the second call to @build_collection.commit), leaving only a single `rebuild_suggesters` and call it a day.
To run in once for each configured solr replica, we need the following:
* ENV[DIRECT_URLS_TO_SOLR_REPLICAS]: A space-delimited set of urls of the form …
=> Build suggesters "manually" against each solr replica

Gemfile.lock, config/initializers/explicit_proxy_host.rb
There appears to be a subtle interaction or bug between ingress-nginx and Rack in this case. Even with the upstream-vhost set and use-forwarded-headers unset, the Ingress host is being supplied as X-Forwarded-Host. Even with use-forwarded-headers set, the X-Forwarded-Host is getting the ingress host.
In Rack, the forwarded_authority takes precedence over the host_authority and server_authority... So, here we try to ensure that our value, supplied via process environment, is written into the forwarded host environment variable at the first position in the middleware stack.
=> Add a middleware to force the HTTP Host
